### ISSUE TITLE
Another Take

### ISSUE THREAD

**Issue by paulushub** [ITAgnesmeyer/Diga.WebView2#2]
Attached is another take of these sources. It is based on **V1077444** and so support runtime `1077444 or later`.
1. For the runtime you can download the WebView2 Runtime, extract the the zip/nuget files and copy the **runtime** folder or all the contents to the **Library** in the source code subdirectory. The included runtime is `microsoft.web.webview2.1.0.864.35`.
2. Added WPF supports
3. Supports multiple frameworks from the same sources .NET4.0, 4.5, 4.6, 4.7, 4.8, NET 5.0, .NET Standard 2.1 etc
4. Removed the other dependent packages like `MimeTypeExtension` for simplicity.
5. Renamed `SourceChangedEventArgs` to `WebSourceChangedEventArgs` to avoid conflict on WPF.
6. **Update** Changed the base of the `WebView` WinForms control to `Control`, from `UserControl`.

This is an initial cut, could be improved further. Currently, I need a WPF/WinForms browser control for .NET 4.0+ to test SVG renderers. This is not a fork, the project structure is modified. So, I decided to post it for anyone interested:

[Diga.WebView2.zip](https://github.com/ITAgnesmeyer/Diga.WebView2/files/6721215/Diga.WebView2.zip)

**Comment by ITAgnesmeyer** [comment]
nice work,
I will be happy to review the changes. If these fit I will add the changes. Please be patient. Since I'm a bit busy at the moment.

**Comment by ITAgnesmeyer** [comment]
Dear paulushub,
I take a first Look at your Changes:
You are right with VS> = 2019, the sources could each be combined in one project. The separation was wanted by us. The projects may be combined at a later point in time.

The framework versions 4.0 - 4.7.1 are not supported in this project. 
The background to this is as follows. 
Versions 4.0 - 4.7.1 are outdated versions of the framework. 
Existing projects should always be updated to the latest version. If this is not possible, the project has a big problem.

NET Standard 2.1 makes no sense, as these projects can only be used in NET Core. For this reason, NET Core DLLs are also accessed directly here. 
Only Std-2.0 would make sense, as these DLL's are supported by other types of projects. Since this project is based on Windows, the 2 project types NET-Core and NET-Framework are offered here.

Update your Target -Projects please.

**Comment by paulushub** [comment]
@ITAgnesmeyer Thanks for reviewing it.
> The separation was wanted by us. The projects may be combined at a later point in time.

The **Diga.WebView2.Interop.dll** is mostly not usable on its own, so better to combine with **Diga.WebView2.Wrapper.dll** to create something like **Diga.WebView2.Code.dll** (as done by Microsoft: Microsoft.Web.WebView2.Core.dll), with **Diga.WebView2.Interop.dll** sources in a separate folder **Interop**.

> Existing projects should always be updated to the latest version. If this is not possible, the project has a big problem.

For enterprise projects, this is not easily an option. Many are still limited to VS 2015 and many big systems like MATLAB are still based on .NET 4.0.

Currently, Microsoft's own release targets .NET 4.5 and .NET Core 3.0 but the tutorial samples recommend .NET 4.6.1.
And implementations like [michael-russin/webview2-control](https://github.com/michael-russin/webview2-control)  recently downgraded to .NET 4.5.

> Only Std-2.0 would make sense, as these DLL's are supported by other types of projects. 

According to Microsoft,

>.NET Standard is still needed for libraries that can be used by multiple .NET implementations. 
> We recommend you target .NET Standard in the following scenarios:
> * Use netstandard2.0 to share code between .NET Framework and all other implementations of .NET.
> * Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.

The point here is .NET Standard 2.0 requires .NET 4.6.1+. If you read the footnote, there are several issues even with this, so I avoid the .NET Standard completely when targeting < .NET .NET 4.6.1.

See [.NET implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)

So for my public projects, and for the targets **Diga.WebView2.WinForms.dll** and **Diga.WebView2.Wpf.dll**, I usually have the following:
1. .NET 4.0 - .NET 4.8, each with its own version DLL
2. .Net Core 3.0/3.1 with Std 2.1 DLLs
3. .NET 5.0/6.0 with Std 2.1 DLLs

**Comment by paulushub** [comment]
> Use these Implementations. for Frameworks < 4.7.2

 michael-russin/webview2-control is old, Microsoft.Web.WebView2.Core.dll is native (so no Any CPU).

> We decided to support only >= 4.7.2

No problem, I did the port for my test applications and will continue develop/update it.
