### ISSUE TITLE
How I can use the repo to watch local MP4 file in Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ITAgnesmeyer/Diga.WebView2#3]
Hello:
I found your repo, it seems to be interesting.  However, I can’t find useful code example for my needs.
For example, I have one MP4 file: C:\Video2\1.mp4.
I can launch ME Edge, and press Ctrl-O to open this mp4 file and play it in Edge.
I want to do the same in a WinForm app. I can add one button (Button1), and if I click on Button1, then I want to launch WebView2 and begin to play the MP4 file.
For MS WebView2, I can add one WebView2 control to Form1, and call some method, like:
webView2.Source = new Uri(@"C:\Video2\1.mp4");
To view the MP4 video.
Let me know how I can do the same in your repo.
By the way, I want to know 2 most important features, which if not impossible, but difficult.
First, can I get the DOM element in your repo?  
Like: var some_objs = Document.getElementsByClassName(“class_name1”).
Second, can I upload some file to one web page.  If I can visit youtube, and I want to upload the MP4 video:
"C:\Video2\1.mp4" to my youtube channel.
Please advise!
Thanks,

**Comment by ITAgnesmeyer** [comment]
Hello:
you can paly a local flie like this.
Uri uri = new Uri(@"C:\Video2\1.mp4");
webView2.Navigate(uri.AbsolutePath);

Currently you cannot manipulate DOM from C# directly.
Microsoft do not support full IDispatch for Scripting-Objects.

However, you can execute JavaScript functions and intercept events.
Please take a look at WebView2WrapperFormsTest.Core or WebView2WrapperWinFormsTest
There is an "S" button at the top of the application, and when you click the button, an HTML button is added to the current document.
And an event is linked to the form. This is currently experimental.
Please feel free to experiment yourself.
If you've found a good solution yourself, let me know.

Best regards
Your ITAgnesmeyer-Team.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, now I can play single video using the repo.
However, if I want to play 2 MP4 videos using the repo, how I can do this?
What I want is like MS Edge using mulitple tabs, and each tab is playing one MP4 file.
Please advise.
By the way, I tried to download the source code and want to see how to use the "S" button.
But I can't see WebView2WrapperFormsTest.Core or WebView2WrapperWinFormsTest
I see the following:
WebView2WrapperWinFormsTest.Core and WebView2WrapperWinFormsTest.Core
But I can't see it from WinForm designer, I got errors:
The designer could not be shown for this file because none of the classes within it can be designed. The designer inspected the following classes in the file: Form1 --- The base class 'System.Windows.Forms.Form' could not be loaded. Ensure the assembly has been referenced and that all projects have been built. 
I tried both VS 2019 and VS 2022, I got the same errors.
Please advise!

**Comment by ITAgnesmeyer** [comment]
Hello,
MS-Edge ist an full Application. Diga.WebView2 is only a control.
You have to create it by yoursoefle.
add tabs on your application and add on each tab a WebView2-Control

Second:
WebView2WrapperWinFormsTest.Core
has only linked Files from 
WebView2WrapperWinFormsTest
Please make sure that all frameworks are installed on your System. So the frameworks
net5.0;net6.0;net5.0-windows; net6.0-windows, net472, standard2.0, standard2.1

WebView2WrapperWinFormsTest*
Before you open the Desgner you have to compile. Otherwise the needed files are not present.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I want to play 2 videos, using the following code:

        private void button1_Click(object sender, EventArgs e)
        {
            List<string> play_list = new();
            play_list.Add(@"C:\Videos\1.mp4";);
            play_list.Add(@"C:\Videos\2.mp4";);
            foreach(string video1 in play_list)
            {
                Uri uri = new(video1);
                webView1.Navigate(uri.AbsolutePath);
                webView1.Refresh();
            }
        }

But the first video is simply skipped, webview just play the last video.
Please advise how to fix this.

**Comment by ITAgnesmeyer** [comment]
Hallo,

Yes, the control does what it should. ;)
You can create an HTML file for your requirement and load it.
```
<html>
<head>
</head>
<body>
	<video controls autoplay name = "media">
		<source src="test1.mp3" type="audio/mpeg">
	</video>
	<video controls autoplay name = "media2">
		<source src="test2.mp3" type="audio/mpeg">
	</video>
</body>
</html>
```
You can then load this local file.

alerterntiv you can also use the monitoring url.
in WebView2WrapperWinFormsTest you can load:
https://5b834d57-0891-4730-b6ba-c793b4e76468/mp3test/testmp3.html
