### ISSUE TITLE
WebView doesn't load webpage because IsCreated is false

### ISSUE THREAD

**Issue by Tony20221** [ITAgnesmeyer/Diga.WebView2#4]
I created a .NET 6 Winforms app. Placed the Diga.WebView2.WinForms.WebView control on the form with a Go button. The Go handler sets the url property but the control doesn't load anything. Upon inspecting the source of  WebView control, it's checking the value of CheckIsCreatedOrEnded which checks the value of the IsCreated value. In my case IsCreated is false. Why is it false if the control is showing on the form during runtime? What am I missing?

It didn't work when using the Nuget package but it worked when referencing the Diga.WebView2.WinForms project. I don't know why.

**Comment by ITAgnesmeyer** [comment]
Please also add the package "Diga.WebView2.Wrapper"

**Comment by ITAgnesmeyer** [comment]
ISSU Closed
