### ISSUE TITLE
Context Menu not showing

### ISSUE THREAD

**Issue by chrisih** [ITAgnesmeyer/Diga.WebView2#5]
Hi,

I greatly appreciate your work. Showing reports works fine, I just have a problem showing / modifying the ContextMenu for a WebBrowser. Is there any magic to be done for that?
I currently have this code:

```
                  <wpf:WebView HorizontalAlignment="Stretch" VerticalAlignment="Stretch" utils:Utils.BindableSource="{Binding HtmlPage}" NavigationCompleted="WebBrowser_LoadCompleted" >
                    <wpf:WebView.ContextMenu>
                      <ContextMenu>
                        <ContextMenu.Items>
                          <MenuItem Header="{DynamicResource Commands:ShowXmlSource}" Command="{Binding ShowXmlSourceCommand}" />
                        </ContextMenu.Items>
                      </ContextMenu>
                    </wpf:WebView.ContextMenu>
                  </wpf:WebView>
```
But on right-click, nothing happens - not even the browser built-in context menu is shown...

Thanks for your work

best regards
Christian

**Comment by ITAgnesmeyer** [comment]
Hi Christian,

yes you are right. 
So far this is not possible. We are currently implementing V10118539 or
V10121039.
Please look at the sources of WebView2WrapperWpfTest. Here we have included a small example of how you can display a ContextMenu. This is currently not included in the NuGet package.
If you want to try this, you have to check out the sources.

Regards
Guido

**Comment by ITAgnesmeyer** [comment]
Now it is possible to create or modify user Context Menues:
Diga.WebView2.Wpf 18.0.1
Diga.WebView2.WinForms 18.0.1
Example:[WebView2WrapperWinFormsTest=>Form1.cs=>webView1_ContextMenuRequested](
https://github.com/ITAgnesmeyer/Diga.WebView2/blob/a6b2014f5ccc17193e211eb9672ddbbd4f85b41c/WebView2WrapperWinFormsTest/Form1.cs#L705)
